export const IPCChannels = {
  TABS_CREATE: 'tabs:create',
  TABS_CLOSE: 'tabs:close',
  TABS_ACTIVATE: 'tabs:activate',
  TABS_LIST: 'tabs:list',
  TABS_UPDATE_META: 'tabs:update-meta',
  TABS_NAVIGATE: 'tabs:navigate',
  TABS_REFRESH: 'tabs:refresh',
  TABS_RELOAD: 'tabs:reload',
  TABS_FORCE_UNLOAD: 'tabs:force-unload',
  TABS_STATE_PUSH: 'tabs:state',
  CONFIG_GET: 'config:get',
  CONFIG_UPDATE: 'config:update',
  BOOKMARK_LIST: 'bookmarks:list',
  BOOKMARK_ADD: 'bookmarks:add',
  BOOKMARK_UPDATE: 'bookmarks:update',
  BOOKMARK_DELETE: 'bookmarks:delete',
  BOOKMARK_SEARCH: 'bookmarks:search',
  BOOKMARK_SYNC: 'bookmarks:sync',
  BOOKMARK_INCREMENT_VISIT: 'bookmarks:increment-visit',
  BOOKMARK_BATCH: 'bookmarks:batch',
  FOLDER_LIST: 'folders:list',
  FOLDER_CREATE: 'folders:create',
  FOLDER_UPDATE: 'folders:update',
  FOLDER_DELETE: 'folders:delete',
  AUTH_LOGIN: 'auth:login',
  AUTH_LOGOUT: 'auth:logout',
  AUTH_GET_CURRENT: 'auth:get-current',
  AUTH_LIST_ACCOUNTS: 'auth:list-accounts'
} as const;

export type IPCChannel = (typeof IPCChannels)[keyof typeof IPCChannels];
